CREATE TABLE `usr` (
  `uuid` char(32) NOT NULL,
  `usr` varchar(50) NOT NULL COMMENT 'sign in account',
  `pwd` varchar(86) NOT NULL COMMENT 'sha512 encode base64 url safe',
  `dept` char(32) NOT NULL,
  `displayId` varchar(50) NOT NULL COMMENT 'display id',
  `name` varchar(50) NOT NULL COMMENT 'full name',
  `display` varchar(50) NOT NULL COMMENT 'display name',
  `gender` int(11) NOT NULL DEFAULT '0' COMMENT '0 female, 1 male',
  `email` varchar(100) NOT NULL,
  `ext` varchar(5) DEFAULT NULL COMMENT '分機',
  `mobile` varchar(15) NOT NULL,
  `lastRead` timestamp NULL DEFAULT NULL,
  `status` int(11) NOT NULL DEFAULT '1' COMMENT '0 disable 1 enable',
  `cr` timestamp NULL DEFAULT NULL,
  `up` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `crUsr` char(32) DEFAULT NULL,
  `upUsr` char(32) DEFAULT NULL,
  `crIP` varchar(45) DEFAULT NULL,
  `upIP` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`uuid`),
  UNIQUE KEY `uk_usr_account` (`usr`),
  UNIQUE KEY `uk_usr_displayId` (`displayId`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='user table';